ALTER TABLE app_settings
    ADD COLUMN IF NOT EXISTS primary_color VARCHAR(20) NOT NULL DEFAULT '#111827';

ALTER TABLE links
    ADD COLUMN IF NOT EXISTS description VARCHAR(255) NOT NULL DEFAULT '' AFTER title,
    ADD COLUMN IF NOT EXISTS is_featured TINYINT(1) NOT NULL DEFAULT 0 AFTER open_mode,
    ADD COLUMN IF NOT EXISTS click_count BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER is_active;
